# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fs1CFsb3Tm4F-QzM6UUpbuYgw0B_VyjO
"""



"""PERFECT NUMBER"""

n=int(input("entre a number"))
i=1
sum=0
for i in range(1,n):
    if i%n==0:
     sum+=i
print("sum=",sum)
if(sum==n):
  print("perfect number")
else:
  print("not a perfect number")



